import React, { useState, useMemo } from "react";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { Search, Gift, Plus, Minus, Package, Sparkles } from "lucide-react";
import { formatCurrency } from "@/lib/utils";
import type { ProductSKUOut } from "@/lib/api";
import { getErrorMessage } from "@/lib/errors";

export interface GiftSetCustomPayload {
  name: string;
  items: Array<{ sku: string; quantity: number; product_name: string; retail_price: number }>;
  packagingCost: number;
  totalRetailPrice: number;
  resellerPrice: number;
  notes?: string;
}

interface GiftSetBuilderModalProps {
  isOpen: boolean;
  onClose: () => void;
  products: ProductSKUOut[];
  onSaveGiftSet: (payload: GiftSetCustomPayload) => Promise<void>;
  title?: string;
}

export function GiftSetBuilderModal({
  isOpen,
  onClose,
  products,
  onSaveGiftSet,
  title = "Build Custom Gift Set",
}: GiftSetBuilderModalProps) {
  const [selectedItems, setSelectedItems] = useState<Record<string, number>>({});
  const [customName, setCustomName] = useState("");
  const [packagingCost, setPackagingCost] = useState<number>(100);
  const [notes, setNotes] = useState("");
  const [search, setSearch] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // Eligible spreads/products to pack inside the gift set
  const availableProducts = useMemo(() => {
    return (products || []).filter(p => p.sku !== "SKU" && p.is_active !== false);
  }, [products]);

  const filteredProducts = useMemo(() => {
    const q = search.toLowerCase().trim();
    if (!q) return availableProducts;
    return availableProducts.filter(p =>
      p.product_name.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q)
    );
  }, [availableProducts, search]);

  // Calculate items breakdown and pricing
  const { selectedList, itemsSubtotal } = useMemo(() => {
    const list: Array<{ product: ProductSKUOut; quantity: number; itemTotal: number }> = [];
    let subtotal = 0;

    Object.entries(selectedItems).forEach(([sku, qty]) => {
      if (qty > 0) {
        const prod = availableProducts.find(p => p.sku === sku);
        if (prod) {
          const itemTotal = qty * Number(prod.retail_price || 0);
          subtotal += itemTotal;
          list.push({ product: prod, quantity: qty, itemTotal });
        }
      }
    });

    return { selectedList: list, itemsSubtotal: subtotal };
  }, [selectedItems, availableProducts]);

  const calculatedRetailPrice = itemsSubtotal + Number(packagingCost || 0);
  const calculatedResellerPrice = Math.round(calculatedRetailPrice * 0.85);

  // Auto-generate a descriptive default name if user hasn't typed one
  const autoGeneratedName = useMemo(() => {
    if (selectedList.length === 0) return "Custom Gift Set Box";
    const itemSummary = selectedList
      .map(i => `${i.quantity}x ${i.product.product_name.replace(/Spread|Sauce/gi, "").trim()}`)
      .join(" + ");
    return `Gift Set (${itemSummary})`;
  }, [selectedList]);

  const finalGiftSetName = customName.trim() || autoGeneratedName;

  const handleQtyChange = (sku: string, delta: number) => {
    setSelectedItems(prev => {
      const current = prev[sku] || 0;
      const next = Math.max(0, current + delta);
      if (next === 0) {
        const copy = { ...prev };
        delete copy[sku];
        return copy;
      }
      return { ...prev, [sku]: next };
    });
  };

  const handleSave = async () => {
    if (selectedList.length === 0) {
      alert("Please select at least 1 spread or product to include in the Gift Set.");
      return;
    }

    setIsSaving(true);
    try {
      await onSaveGiftSet({
        name: finalGiftSetName,
        items: selectedList.map(i => ({
          sku: i.product.sku,
          quantity: i.quantity,
          product_name: i.product.product_name,
          retail_price: Number(i.product.retail_price || 0),
        })),
        packagingCost: Number(packagingCost || 0),
        totalRetailPrice: calculatedRetailPrice,
        resellerPrice: calculatedResellerPrice,
        notes,
      });

      // Reset state on successful save
      setSelectedItems({});
      setCustomName("");
      setPackagingCost(100);
      setNotes("");
      setSearch("");
      onClose();
    } catch (err: unknown) {
      alert(`Error saving gift set: ${getErrorMessage(err)}`);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={title} size="3xl">
      <div className="space-y-5 text-slate-700">
        
        {/* Rule Banner */}
        <div className="flex items-start gap-3 p-4 bg-amber-50 border border-amber-200 rounded-2xl text-xs font-semibold text-amber-900 leading-relaxed shadow-2xs">
          <Sparkles className="text-amber-600 shrink-0 mt-0.5" size={18} />
          <div>
            <strong className="font-extrabold uppercase block tracking-wider text-amber-950">
              Gift Set Pricing Rule: Original Items Price + ₱100 Packaging
            </strong>
            Customize any combination of spreads or products based on customer request. The final retail price is automatically calculated as: 
            <span className="font-mono font-black text-amber-900 ml-1">Sum of selected items SRP + ₱100.00 packaging fee</span>.
          </div>
        </div>

        {/* 2-Column Desktop Layout */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-5">
          
          {/* Left Column: Product Selector */}
          <div className="md:col-span-7 space-y-3 flex flex-col">
            <div className="flex items-center justify-between gap-2">
              <span className="text-xs font-black uppercase text-slate-500 tracking-wider">
                1. Select Contents to Include
              </span>
              <span className="text-[11px] font-bold text-slate-400">
                {selectedList.length} item{selectedList.length !== 1 ? "s" : ""} selected
              </span>
            </div>

            {/* Search Input */}
            <div className="relative">
              <Search className="absolute left-3 top-2.5 text-slate-400" size={15} />
              <input
                type="text"
                placeholder="Search spreads or products..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="w-full py-2 text-xs font-semibold rounded-xl border border-slate-200 bg-white outline-none focus:ring-2 focus:ring-primary/20"
                style={{ paddingLeft: "2.25rem", paddingRight: "0.75rem" }}
              />
            </div>

            {/* Products List Scrollable Container */}
            <div className="max-h-72 overflow-y-auto rounded-2xl border border-slate-200 bg-white divide-y divide-slate-100 p-1 space-y-1">
              {filteredProducts.length === 0 ? (
                <div className="py-8 text-center text-xs font-medium text-slate-400">
                  No matching products found
                </div>
              ) : (
                filteredProducts.map(p => {
                  const qty = selectedItems[p.sku] || 0;
                  const price = Number(p.retail_price || 0);

                  return (
                    <div
                      key={p.sku}
                      className={`flex items-center justify-between p-2.5 rounded-xl transition-colors ${
                        qty > 0 ? "bg-amber-50/60 border border-amber-200/60" : "hover:bg-slate-50"
                      }`}
                    >
                      <div className="min-w-0 pr-2">
                        <div className="text-xs font-bold text-slate-850 truncate">{p.product_name}</div>
                        <div className="flex items-center gap-2 text-[10px] text-slate-400 font-mono mt-0.5">
                          <span>{p.sku}</span>
                          <span>•</span>
                          <span className="font-bold text-slate-700">{formatCurrency(price)}</span>
                        </div>
                      </div>

                      <div className="flex items-center gap-1.5 shrink-0">
                        <button
                          type="button"
                          onClick={() => handleQtyChange(p.sku, -1)}
                          disabled={qty === 0}
                          className="h-7 w-7 rounded-lg border border-slate-200 bg-white text-slate-600 hover:bg-slate-100 disabled:opacity-40 flex items-center justify-center cursor-pointer"
                        >
                          <Minus size={12} />
                        </button>
                        <span className="w-6 text-center text-xs font-mono font-black text-slate-800">
                          {qty}
                        </span>
                        <button
                          type="button"
                          onClick={() => handleQtyChange(p.sku, 1)}
                          className="h-7 w-7 rounded-lg border border-amber-300 bg-amber-100 text-amber-900 hover:bg-amber-200 flex items-center justify-center font-bold cursor-pointer"
                        >
                          <Plus size={12} />
                        </button>
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Right Column: Pricing & Live Breakdown Summary */}
          <div className="md:col-span-5 space-y-4 flex flex-col justify-between bg-slate-50 border border-slate-200 rounded-2xl p-4">
            
            <div className="space-y-3">
              <span className="text-xs font-black uppercase text-slate-500 tracking-wider block border-b border-slate-200 pb-2">
                2. Live Price Breakdown
              </span>

              {/* Items Selected List */}
              <div className="space-y-1.5 max-h-36 overflow-y-auto">
                {selectedList.length === 0 ? (
                  <p className="text-xs italic text-slate-400 py-4 text-center">
                    Select products on the left to see itemized cost breakdown.
                  </p>
                ) : (
                  selectedList.map(item => (
                    <div key={item.product.sku} className="flex justify-between items-center text-xs font-semibold text-slate-700">
                      <span className="truncate pr-2">{item.quantity}x {item.product.product_name}</span>
                      <span className="font-mono font-bold shrink-0">{formatCurrency(item.itemTotal)}</span>
                    </div>
                  ))
                )}
              </div>

              {/* Subtotals & Fees */}
              <div className="space-y-2 pt-2 border-t border-slate-200 text-xs font-bold text-slate-600">
                <div className="flex justify-between items-center">
                  <span className="text-slate-500">Selected Items Total:</span>
                  <span className="font-mono text-slate-800 font-extrabold">{formatCurrency(itemsSubtotal)}</span>
                </div>

                <div className="flex justify-between items-center gap-2">
                  <span className="text-slate-600 flex items-center gap-1">
                    <Package size={13} className="text-amber-700" /> Packaging &amp; Box:
                  </span>
                  <div className="flex items-center gap-1">
                    <span className="font-mono text-amber-700">+₱</span>
                    <input
                      type="number"
                      min="0"
                      step="5"
                      value={packagingCost}
                      onChange={e => setPackagingCost(Number(e.target.value))}
                      className="w-16 px-2 py-0.5 text-right font-mono font-black text-amber-900 border border-amber-300 rounded-lg bg-white outline-none"
                    />
                  </div>
                </div>
              </div>

              {/* Total Calculated SRP Highlight Box */}
              <div className="p-3 bg-white border-2 border-amber-300 rounded-xl shadow-2xs space-y-1">
                <span className="text-[10px] uppercase font-black tracking-wider text-amber-800 block">
                  Calculated Gift Set Retail Price (SRP)
                </span>
                <div className="text-xl font-mono font-black text-amber-950">
                  {formatCurrency(calculatedRetailPrice)}
                </div>
                <div className="text-[10px] text-slate-400 font-semibold">
                  Formula: {formatCurrency(itemsSubtotal)} items + {formatCurrency(packagingCost)} packaging
                </div>
              </div>

              {/* Gift Set Name & Notes */}
              <div className="space-y-2 pt-1">
                <div>
                  <label className="block text-[11px] font-bold text-slate-600 mb-1">
                    Gift Set Name
                  </label>
                  <input
                    type="text"
                    placeholder={autoGeneratedName}
                    value={customName}
                    onChange={e => setCustomName(e.target.value)}
                    className="w-full px-3 py-1.5 text-xs font-semibold rounded-xl border border-slate-200 bg-white outline-none focus:ring-2 focus:ring-primary/20"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-slate-600 mb-1">
                    Notes / Customer Request (Optional)
                  </label>
                  <input
                    type="text"
                    placeholder="e.g., Requested custom green ribbon & holiday tag"
                    value={notes}
                    onChange={e => setNotes(e.target.value)}
                    className="w-full px-3 py-1.5 text-xs font-semibold rounded-xl border border-slate-200 bg-white outline-none focus:ring-2 focus:ring-primary/20"
                  />
                </div>
              </div>

            </div>

            {/* Modal Actions */}
            <div className="pt-3 border-t border-slate-200 flex gap-2">
              <Button
                variant="outline"
                onClick={onClose}
                disabled={isSaving}
                className="w-1/3 text-xs font-bold rounded-xl"
              >
                Cancel
              </Button>
              <Button
                variant="primary"
                onClick={handleSave}
                isLoading={isSaving}
                disabled={selectedList.length === 0 || isSaving}
                className="w-2/3 text-xs font-black uppercase rounded-xl bg-amber-800 hover:bg-amber-900 border-amber-700"
                leftIcon={<Gift size={14} />}
              >
                Save Gift Set ({formatCurrency(calculatedRetailPrice)})
              </Button>
            </div>

          </div>

        </div>

      </div>
    </Modal>
  );
}
