"""Initial schema

Revision ID: fe613a4f6b32
Revises: 
Create Date: 2026-07-11 09:23:41.498078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe613a4f6b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cleaning_tasks', 'last_done_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_cleaning_tasks_id'), 'cleaning_tasks', ['id'], unique=False)
    op.alter_column('consignment_deliveries', 'delivery_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('consignment_deliveries', 'is_paid',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('consignment_deliveries', 'payment_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('idx_consignment_deliveries_partner_id'), table_name='consignment_deliveries')
    op.create_index(op.f('ix_consignment_deliveries_delivery_date'), 'consignment_deliveries', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_consignment_deliveries_id'), 'consignment_deliveries', ['id'], unique=False)
    op.alter_column('consignment_items', 'reseller_price_snapshot',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('consignment_items', 'cost_per_unit_snapshot',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('consignment_items', 'store_price_snapshot',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_consignment_items_delivery_id'), table_name='consignment_items')
    op.drop_index(op.f('idx_consignment_items_sku'), table_name='consignment_items')
    op.create_index(op.f('ix_consignment_items_id'), 'consignment_items', ['id'], unique=False)
    op.alter_column('consignment_partners', 'discount_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.1000'))
    op.alter_column('consignment_partners', 'minimum_order_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1500.00'))
    op.drop_constraint(op.f('consignment_partners_name_key'), 'consignment_partners', type_='unique')
    op.create_index(op.f('ix_consignment_partners_id'), 'consignment_partners', ['id'], unique=False)
    op.create_index(op.f('ix_consignment_partners_name'), 'consignment_partners', ['name'], unique=True)
    op.alter_column('discount_tiers', 'min_subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('discount_tiers', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_discount_tiers_id'), 'discount_tiers', ['id'], unique=False)
    op.drop_index(op.f('idx_gift_set_items_gift_set_id'), table_name='gift_set_items')
    op.drop_index(op.f('idx_gift_set_items_sku'), table_name='gift_set_items')
    op.alter_column('ingredient_batches', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_ingredient_batches_expiry_date'), table_name='ingredient_batches')
    op.drop_index(op.f('idx_ingredient_batches_raw_ingredient_id'), table_name='ingredient_batches')
    op.create_index(op.f('ix_ingredient_batches_expiry_date'), 'ingredient_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_ingredient_batches_id'), 'ingredient_batches', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_batches_raw_ingredient_id'), 'ingredient_batches', ['raw_ingredient_id'], unique=False)
    op.alter_column('inventory_transactions', 'qty',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_inventory_transactions_raw_ingredient_id'), table_name='inventory_transactions')
    op.drop_index(op.f('idx_inventory_transactions_sku'), table_name='inventory_transactions')
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_raw_ingredient_id'), 'inventory_transactions', ['raw_ingredient_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_sku'), 'inventory_transactions', ['sku'], unique=False)
    op.alter_column('maintenance_assets', 'replacement_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_maintenance_assets_id'), 'maintenance_assets', ['id'], unique=False)
    op.alter_column('overhead_configs', 'cost_per_month',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('overhead_configs', 'cost_per_day',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('overhead_configs', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('overhead_configs_particular_key'), 'overhead_configs', type_='unique')
    op.create_index(op.f('ix_overhead_configs_id'), 'overhead_configs', ['id'], unique=False)
    op.create_index(op.f('ix_overhead_configs_particular'), 'overhead_configs', ['particular'], unique=True)
    op.alter_column('product_skus', 'retail_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('product_skus', 'reseller_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('product_skus', 'cost_override',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('product_skus', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('product_skus', 'density_multiplier',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('1.0000'))
    op.create_index(op.f('ix_product_skus_product_name'), 'product_skus', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_skus_sku'), 'product_skus', ['sku'], unique=False)
    op.alter_column('production_batches', 'batch_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('production_batches', 'actual_yield',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('production_batches', 'staff_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_production_batches_batch_date'), 'production_batches', ['batch_date'], unique=False)
    op.create_index(op.f('ix_production_batches_id'), 'production_batches', ['id'], unique=False)
    op.create_foreign_key(None, 'production_batches', 'product_skus', ['sku'], ['sku'], ondelete='SET NULL')
    op.alter_column('production_plans', 'plan_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_constraint(op.f('production_plans_plan_date_key'), 'production_plans', type_='unique')
    op.create_index(op.f('ix_production_plans_id'), 'production_plans', ['id'], unique=False)
    op.create_index(op.f('ix_production_plans_plan_date'), 'production_plans', ['plan_date'], unique=True)
    op.create_index(op.f('ix_production_targets_id'), 'production_targets', ['id'], unique=False)
    op.create_foreign_key(None, 'production_targets', 'product_skus', ['sku'], ['sku'], ondelete='CASCADE')
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.alter_column('raw_ingredients', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('raw_ingredients', 'net_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('raw_ingredients', 'cost_per_gram_unit',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('raw_ingredients', 'available_stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('raw_ingredients', 'reorder_level',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('raw_ingredients_name_key'), 'raw_ingredients', type_='unique')
    op.create_index(op.f('ix_raw_ingredients_id'), 'raw_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_raw_ingredients_name'), 'raw_ingredients', ['name'], unique=True)
    op.alter_column('recipe_items', 'base_qty',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_recipe_items_raw_ingredient_id'), table_name='recipe_items')
    op.drop_index(op.f('idx_recipe_items_recipe_id'), table_name='recipe_items')
    op.create_index(op.f('ix_recipe_items_id'), 'recipe_items', ['id'], unique=False)
    op.alter_column('recipes', 'yield_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('recipes', 'portion_size',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.alter_column('reseller_order_items', 'price_snapshot',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index(op.f('idx_reseller_order_items_order_id'), table_name='reseller_order_items')
    op.drop_index(op.f('idx_reseller_order_items_sku'), table_name='reseller_order_items')
    op.create_index(op.f('ix_reseller_order_items_id'), 'reseller_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_reseller_order_items_order_id'), 'reseller_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_reseller_order_items_sku'), 'reseller_order_items', ['sku'], unique=False)
    op.alter_column('reseller_orders', 'order_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('reseller_orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'discount_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'grand_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'is_paid',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_reseller_orders_id'), 'reseller_orders', ['id'], unique=False)
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('suppliers_name_key'), 'suppliers', type_='unique')
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'created_at')
    op.alter_column('warehouse_stocks', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('warehouse_stocks', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('idx_warehouse_stocks_sku'), table_name='warehouse_stocks')
    op.drop_index(op.f('idx_warehouse_stocks_warehouse_id'), table_name='warehouse_stocks')
    op.drop_constraint(op.f('unique_warehouse_raw'), 'warehouse_stocks', type_='unique')
    op.drop_constraint(op.f('unique_warehouse_sku'), 'warehouse_stocks', type_='unique')
    op.create_index(op.f('ix_warehouse_stocks_id'), 'warehouse_stocks', ['id'], unique=False)
    op.alter_column('warehouses', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('warehouses_name_key'), 'warehouses', type_='unique')
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.create_unique_constraint(op.f('warehouses_name_key'), 'warehouses', ['name'])
    op.alter_column('warehouses', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_warehouse_stocks_id'), table_name='warehouse_stocks')
    op.create_unique_constraint(op.f('unique_warehouse_sku'), 'warehouse_stocks', ['warehouse_id', 'sku'])
    op.create_unique_constraint(op.f('unique_warehouse_raw'), 'warehouse_stocks', ['warehouse_id', 'raw_ingredient_id'])
    op.create_index(op.f('idx_warehouse_stocks_warehouse_id'), 'warehouse_stocks', ['warehouse_id'], unique=False)
    op.create_index(op.f('idx_warehouse_stocks_sku'), 'warehouse_stocks', ['sku'], unique=False)
    op.alter_column('warehouse_stocks', 'quantity',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('warehouse_stocks', 'warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'])
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.create_unique_constraint(op.f('suppliers_name_key'), 'suppliers', ['name'])
    op.alter_column('suppliers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_reseller_orders_id'), table_name='reseller_orders')
    op.alter_column('reseller_orders', 'is_paid',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('reseller_orders', 'grand_total',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'discount_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'discount_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('reseller_orders', 'order_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_reseller_order_items_sku'), table_name='reseller_order_items')
    op.drop_index(op.f('ix_reseller_order_items_order_id'), table_name='reseller_order_items')
    op.drop_index(op.f('ix_reseller_order_items_id'), table_name='reseller_order_items')
    op.create_index(op.f('idx_reseller_order_items_sku'), 'reseller_order_items', ['sku'], unique=False)
    op.create_index(op.f('idx_reseller_order_items_order_id'), 'reseller_order_items', ['order_id'], unique=False)
    op.alter_column('reseller_order_items', 'price_snapshot',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.alter_column('recipes', 'portion_size',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('recipes', 'yield_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_recipe_items_id'), table_name='recipe_items')
    op.create_index(op.f('idx_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_recipe_items_raw_ingredient_id'), 'recipe_items', ['raw_ingredient_id'], unique=False)
    op.alter_column('recipe_items', 'base_qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_raw_ingredients_name'), table_name='raw_ingredients')
    op.drop_index(op.f('ix_raw_ingredients_id'), table_name='raw_ingredients')
    op.create_unique_constraint(op.f('raw_ingredients_name_key'), 'raw_ingredients', ['name'])
    op.alter_column('raw_ingredients', 'reorder_level',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('raw_ingredients', 'available_stock',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('raw_ingredients', 'cost_per_gram_unit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('raw_ingredients', 'net_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('raw_ingredients', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.alter_column('push_subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'production_targets', type_='foreignkey')
    op.drop_index(op.f('ix_production_targets_id'), table_name='production_targets')
    op.drop_index(op.f('ix_production_plans_plan_date'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_id'), table_name='production_plans')
    op.create_unique_constraint(op.f('production_plans_plan_date_key'), 'production_plans', ['plan_date'])
    op.alter_column('production_plans', 'plan_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'production_batches', type_='foreignkey')
    op.drop_index(op.f('ix_production_batches_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_batch_date'), table_name='production_batches')
    op.alter_column('production_batches', 'staff_hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('production_batches', 'actual_yield',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('production_batches', 'batch_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_skus_sku'), table_name='product_skus')
    op.drop_index(op.f('ix_product_skus_product_name'), table_name='product_skus')
    op.alter_column('product_skus', 'density_multiplier',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('1.0000'))
    op.alter_column('product_skus', 'cost_per_unit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('product_skus', 'cost_override',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('product_skus', 'reseller_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('product_skus', 'retail_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_overhead_configs_particular'), table_name='overhead_configs')
    op.drop_index(op.f('ix_overhead_configs_id'), table_name='overhead_configs')
    op.create_unique_constraint(op.f('overhead_configs_particular_key'), 'overhead_configs', ['particular'])
    op.alter_column('overhead_configs', 'hourly_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('overhead_configs', 'cost_per_day',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('overhead_configs', 'cost_per_month',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_index(op.f('ix_maintenance_assets_id'), table_name='maintenance_assets')
    op.alter_column('maintenance_assets', 'replacement_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_transactions_sku'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_raw_ingredient_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.create_index(op.f('idx_inventory_transactions_sku'), 'inventory_transactions', ['sku'], unique=False)
    op.create_index(op.f('idx_inventory_transactions_raw_ingredient_id'), 'inventory_transactions', ['raw_ingredient_id'], unique=False)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('inventory_transactions', 'qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_ingredient_batches_raw_ingredient_id'), table_name='ingredient_batches')
    op.drop_index(op.f('ix_ingredient_batches_id'), table_name='ingredient_batches')
    op.drop_index(op.f('ix_ingredient_batches_expiry_date'), table_name='ingredient_batches')
    op.create_index(op.f('idx_ingredient_batches_raw_ingredient_id'), 'ingredient_batches', ['raw_ingredient_id'], unique=False)
    op.create_index(op.f('idx_ingredient_batches_expiry_date'), 'ingredient_batches', ['expiry_date'], unique=False)
    op.alter_column('ingredient_batches', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('idx_gift_set_items_sku'), 'gift_set_items', ['sku'], unique=False)
    op.create_index(op.f('idx_gift_set_items_gift_set_id'), 'gift_set_items', ['gift_set_id'], unique=False)
    op.drop_index(op.f('ix_discount_tiers_id'), table_name='discount_tiers')
    op.alter_column('discount_tiers', 'discount_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('discount_tiers', 'min_subtotal',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_consignment_partners_name'), table_name='consignment_partners')
    op.drop_index(op.f('ix_consignment_partners_id'), table_name='consignment_partners')
    op.create_unique_constraint(op.f('consignment_partners_name_key'), 'consignment_partners', ['name'])
    op.alter_column('consignment_partners', 'minimum_order_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('1500.00'))
    op.alter_column('consignment_partners', 'discount_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text('0.1000'))
    op.drop_index(op.f('ix_consignment_items_id'), table_name='consignment_items')
    op.create_index(op.f('idx_consignment_items_sku'), 'consignment_items', ['sku'], unique=False)
    op.create_index(op.f('idx_consignment_items_delivery_id'), 'consignment_items', ['delivery_id'], unique=False)
    op.alter_column('consignment_items', 'store_price_snapshot',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('consignment_items', 'cost_per_unit_snapshot',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('consignment_items', 'reseller_price_snapshot',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_consignment_deliveries_id'), table_name='consignment_deliveries')
    op.drop_index(op.f('ix_consignment_deliveries_delivery_date'), table_name='consignment_deliveries')
    op.create_index(op.f('idx_consignment_deliveries_partner_id'), 'consignment_deliveries', ['partner_id'], unique=False)
    op.alter_column('consignment_deliveries', 'payment_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('consignment_deliveries', 'is_paid',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('consignment_deliveries', 'delivery_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cleaning_tasks_id'), table_name='cleaning_tasks')
    op.alter_column('cleaning_tasks', 'last_done_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
