-- Owner weekly dashboard: immutable cost components and ingredient price history.
-- Legacy line items are explicitly labelled estimates because current master
-- costs cannot reconstruct the exact historical component mix.

ALTER TABLE public.consignment_items
  ADD COLUMN IF NOT EXISTS food_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS labor_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS utility_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS cost_status_snapshot VARCHAR(30),
  ADD COLUMN IF NOT EXISTS cost_snapshot_recorded_at TIMESTAMPTZ;

ALTER TABLE public.reseller_order_items
  ADD COLUMN IF NOT EXISTS food_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS labor_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS utility_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS cost_status_snapshot VARCHAR(30),
  ADD COLUMN IF NOT EXISTS cost_snapshot_recorded_at TIMESTAMPTZ;

ALTER TABLE public.market_event_sale_items
  ADD COLUMN IF NOT EXISTS food_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS labor_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS utility_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS total_cost_snapshot DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS cost_status_snapshot VARCHAR(30),
  ADD COLUMN IF NOT EXISTS cost_snapshot_recorded_at TIMESTAMPTZ;

UPDATE public.consignment_items AS item
SET
  food_cost_snapshot = COALESCE(item.food_cost_snapshot, item.cost_per_unit_snapshot, 0),
  labor_cost_snapshot = COALESCE(item.labor_cost_snapshot, product.labor_cost, 0),
  utility_cost_snapshot = COALESCE(item.utility_cost_snapshot, product.utility_cost, 0),
  total_cost_snapshot = COALESCE(
    item.total_cost_snapshot,
    COALESCE(item.cost_per_unit_snapshot, 0)
      + COALESCE(product.labor_cost, 0)
      + COALESCE(product.utility_cost, 0)
  ),
  cost_status_snapshot = COALESCE(item.cost_status_snapshot, 'legacy_estimate'),
  cost_snapshot_recorded_at = COALESCE(item.cost_snapshot_recorded_at, NOW())
FROM public.product_skus AS product
WHERE product.sku = item.sku
  AND (
    item.food_cost_snapshot IS NULL
    OR item.labor_cost_snapshot IS NULL
    OR item.utility_cost_snapshot IS NULL
    OR item.total_cost_snapshot IS NULL
    OR item.cost_status_snapshot IS NULL
    OR item.cost_snapshot_recorded_at IS NULL
  );

UPDATE public.reseller_order_items AS item
SET
  food_cost_snapshot = COALESCE(item.food_cost_snapshot, product.cost_per_unit, 0),
  labor_cost_snapshot = COALESCE(item.labor_cost_snapshot, product.labor_cost, 0),
  utility_cost_snapshot = COALESCE(item.utility_cost_snapshot, product.utility_cost, 0),
  total_cost_snapshot = COALESCE(
    item.total_cost_snapshot,
    COALESCE(product.cost_per_unit, 0)
      + COALESCE(product.labor_cost, 0)
      + COALESCE(product.utility_cost, 0)
  ),
  cost_status_snapshot = COALESCE(item.cost_status_snapshot, 'legacy_estimate'),
  cost_snapshot_recorded_at = COALESCE(item.cost_snapshot_recorded_at, NOW())
FROM public.product_skus AS product
WHERE product.sku = item.sku
  AND (
    item.food_cost_snapshot IS NULL
    OR item.labor_cost_snapshot IS NULL
    OR item.utility_cost_snapshot IS NULL
    OR item.total_cost_snapshot IS NULL
    OR item.cost_status_snapshot IS NULL
    OR item.cost_snapshot_recorded_at IS NULL
  );

UPDATE public.market_event_sale_items AS item
SET
  food_cost_snapshot = COALESCE(item.food_cost_snapshot, product.cost_per_unit, 0),
  labor_cost_snapshot = COALESCE(item.labor_cost_snapshot, product.labor_cost, 0),
  utility_cost_snapshot = COALESCE(item.utility_cost_snapshot, product.utility_cost, 0),
  total_cost_snapshot = COALESCE(
    item.total_cost_snapshot,
    COALESCE(product.cost_per_unit, 0)
      + COALESCE(product.labor_cost, 0)
      + COALESCE(product.utility_cost, 0)
  ),
  cost_status_snapshot = COALESCE(item.cost_status_snapshot, 'legacy_estimate'),
  cost_snapshot_recorded_at = COALESCE(item.cost_snapshot_recorded_at, NOW())
FROM public.product_skus AS product
WHERE product.sku = item.sku
  AND (
    item.food_cost_snapshot IS NULL
    OR item.labor_cost_snapshot IS NULL
    OR item.utility_cost_snapshot IS NULL
    OR item.total_cost_snapshot IS NULL
    OR item.cost_status_snapshot IS NULL
    OR item.cost_snapshot_recorded_at IS NULL
  );

CREATE TABLE IF NOT EXISTS public.ingredient_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_ingredient_id INTEGER NOT NULL
    REFERENCES public.raw_ingredients(id) ON DELETE CASCADE,
  previous_price DOUBLE PRECISION NOT NULL,
  new_price DOUBLE PRECISION NOT NULL,
  previous_net_weight DOUBLE PRECISION NOT NULL,
  new_net_weight DOUBLE PRECISION NOT NULL,
  previous_unit_cost DOUBLE PRECISION NOT NULL,
  new_unit_cost DOUBLE PRECISION NOT NULL,
  changed_by_user_id INTEGER
    REFERENCES public.users(id) ON DELETE SET NULL,
  source VARCHAR(50) NOT NULL DEFAULT 'inventory_edit',
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_ingredient_price_history_ingredient_changed
  ON public.ingredient_price_history(raw_ingredient_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS ix_ingredient_price_history_changed_by
  ON public.ingredient_price_history(changed_by_user_id);

ALTER TABLE public.ingredient_price_history ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ingredient_price_history FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.ingredient_price_history_id_seq FROM anon, authenticated;
